export const IntegrationData = [
  {
    id: 1,
    integrationTitle: 'Airflow',
    integrationImage: 'airflow.png',
    integrationDescription: 'loreum ipsum text',
    integrationStatus: 'roadmap',
    integrationURL: 'concur.live/integrations/airflow',
  },
  {
    id: 2,
    integrationTitle: 'Amazon Glue',
    integrationImage: 'glue.png',
    integrationDescription: 'loreum ipsum text',
    integrationStatus: 'roadmap',
    integrationURL: 'concur.live/integrations/amazon-glue',
  },
  {
    id: 3,
    integrationTitle: 'Amazon S3',
    integrationImage: 's3.png',
    integrationDescription: 'loreum ipsum text',
    integrationStatus: 'roadmap',
    integrationURL: 'concur.live/integrations/amazon-s3',
  },
  {
    id: 4,
    integrationTitle: 'Athena',
    integrationImage: 'athena.png',
    integrationDescription: 'loreum ipsum text',
    integrationStatus: 'roadmap',
    integrationURL: 'concur.live/integrations/athena',
  },
  {
    id: 5,
    integrationTitle: 'Azure AD',
    integrationImage: 'azure-ad.png',
    integrationDescription: 'loreum ipsum text',
    integrationStatus: 'roadmap',
    integrationURL: 'concur.live/integrations/azure-ad',
  },
  {
    id: 6,
    integrationTitle: 'BOX',
    integrationImage: 'box.png',
    integrationDescription: 'loreum ipsum text',
    integrationStatus: 'roadmap',
    integrationURL: 'concur.live/integrations/box',
  },
  {
    id: 7,
    integrationTitle: 'ClickHouse',
    integrationImage: 'clickhouse.png',
    integrationDescription: 'loreum ipsum text',
    integrationStatus: 'roadmap',
    integrationURL: 'concur.live/integrations/clickhouse',
  },
  {
    id: 8,
    integrationTitle: 'Databricks',
    integrationImage: 'databricks.png',
    integrationDescription: 'loreum ipsum text',
    integrationStatus: 'roadmap',
    integrationURL: 'concur.live/integrations/databricks',
  },
  {
    id: 9,
    integrationTitle: 'Delta Lake',
    integrationImage: 'delta-lake.png',
    integrationDescription: 'loreum ipsum text',
    integrationStatus: 'roadmap',
    integrationURL: 'concur.live/integrations/delta-lake',
  },
  {
    id: 10,
    integrationTitle: 'Elasticsearch',
    integrationImage: 'elasticsearch.png',
    integrationDescription: 'loreum ipsum text',
    integrationStatus: 'roadmap',
    integrationURL: 'concur.live/integrations/elasticsearch',
  },
  {
    id: 11,
    integrationTitle: 'Feast',
    integrationImage: 'feast.png',
    integrationDescription: 'loreum ipsum text',
    integrationStatus: 'roadmap',
    integrationURL: 'concur.live/integrations/feast',
  },
  {
    id: 12,
    integrationTitle: 'Google BigQuery',
    integrationImage: 'google-bigquery.png',
    integrationDescription: 'loreum ipsum text',
    integrationStatus: 'roadmap',
    integrationURL: 'concur.live/integrations/google-bigquery',
  },
  {
    id: 13,
    integrationTitle: 'Great Expectations',
    integrationImage: 'great-expectations.png',
    integrationDescription: 'loreum ipsum text',
    integrationStatus: 'roadmap',
    integrationURL: 'concur.live/integrations/great-expectations',
  },
  {
    id: 14,
    integrationTitle: 'Hive',
    integrationImage: 'hive.png',
    integrationDescription: 'loreum ipsum text',
    integrationStatus: 'roadmap',
    integrationURL: 'concur.live/integrations/hive',
  },
  {
    id: 15,
    integrationTitle: 'IBM Db2',
    integrationImage: 'ibm-db2.png',
    integrationDescription: 'loreum ipsum text',
    integrationStatus: 'roadmap',
    integrationURL: 'concur.live/integrations/ibm-db2',
  },
  {
    id: 16,
    integrationTitle: 'Iceberg',
    integrationImage: 'iceberg.png',
    integrationDescription: 'loreum ipsum text',
    integrationStatus: 'roadmap',
    integrationURL: 'concur.live/integrations/iceberg',
  },
  {
    id: 17,
    integrationTitle: 'Kafka',
    integrationImage: 'kafka.png',
    integrationDescription: 'loreum ipsum text',
    integrationStatus: 'roadmap',
    integrationURL: 'concur.live/integrations/kafka',
  },
  {
    id: 18,
    integrationTitle: 'LDAP',
    integrationImage: 'ldap.png',
    integrationDescription: 'loreum ipsum text',
    integrationStatus: 'roadmap',
    integrationURL: 'concur.live/integrations/ldap',
  },
  {
    id: 19,
    integrationTitle: 'Looker',
    integrationImage: 'looker.png',
    integrationDescription: 'loreum ipsum text',
    integrationStatus: 'roadmap',
    integrationURL: 'concur.live/integrations/looker',
  },
  {
    id: 20,
    integrationTitle: 'MYSQL',
    integrationImage: 'mysql.png',
    integrationDescription: 'loreum ipsum text',
    integrationStatus: 'roadmap',
    integrationURL: 'concur.live/integrations/mysql',
  },
  {
    id: 21,
    integrationTitle: 'MariaDB',
    integrationImage: 'mariadb.png',
    integrationDescription: 'loreum ipsum text',
    integrationStatus: 'roadmap',
    integrationURL: 'concur.live/integrations/mariadb',
  },
  {
    id: 22,
    integrationTitle: 'Metabase',
    integrationImage: 'metabase.png',
    integrationDescription: 'loreum ipsum text',
    integrationStatus: 'roadmap',
    integrationURL: 'concur.live/integrations/metabase',
  },
  {
    id: 23,
    integrationTitle: 'Microsoft Exchange',
    integrationImage: 'microsoft-exchange.png',
    integrationDescription: 'loreum ipsum text',
    integrationStatus: 'roadmap',
    integrationURL: 'concur.live/integrations/microsoft-exchange',
  },
  {
    id: 24,
    integrationTitle: 'Microsoft Teams',
    integrationImage: 'microsoft-teams.png',
    integrationDescription: 'loreum ipsum text',
    integrationStatus: 'roadmap',
    integrationURL: 'concur.live/integrations/microsoft-teams',
  },
  {
    id: 25,
    integrationTitle: 'MicrosoftSQL',
    integrationImage: 'microsoft-sql.png',
    integrationDescription: 'loreum ipsum text',
    integrationStatus: 'roadmap',
    integrationURL: 'concur.live/integrations/microsoft-sql',
  },
  {
    id: 26,
    integrationTitle: 'Mode',
    integrationImage: 'mode.png',
    integrationDescription: 'loreum ipsum text',
    integrationStatus: 'roadmap',
    integrationURL: 'concur.live/integrations/mode',
  },
  {
    id: 27,
    integrationTitle: 'MongoDB',
    integrationImage: 'mongodb.png',
    integrationDescription: 'loreum ipsum text',
    integrationStatus: 'roadmap',
    integrationURL: 'concur.live/integrations/mongodb',
  },
  {
    id: 28,
    integrationTitle: 'MongoDB Atlas',
    integrationImage: 'mongodb-atlas.png',
    integrationDescription: 'loreum ipsum text',
    integrationStatus: 'roadmap',
    integrationURL: 'concur.live/integrations/mongodb-atlas',
  },
  {
    id: 29,
    integrationTitle: 'Nifi',
    integrationImage: 'nifi.png',
    integrationDescription: 'loreum ipsum text',
    integrationStatus: 'roadmap',
    integrationURL: 'concur.live/integrations/nifi',
  },
  {
    id: 30,
    integrationTitle: 'Okta',
    integrationImage: 'okta.png',
    integrationDescription: 'loreum ipsum text',
    integrationStatus: 'roadmap',
    integrationURL: 'concur.live/integrations/okta',
  },
  {
    id: 31,
    integrationTitle: 'OneDrive',
    integrationImage: 'onedrive.png',
    integrationDescription: 'loreum ipsum text',
    integrationStatus: 'roadmap',
    integrationURL: 'concur.live/integrations/onedrive',
  },
  {
    id: 32,
    integrationTitle: 'Oracle RDBMS',
    integrationImage: 'oracle-rdbms.png',
    integrationDescription: 'loreum ipsum text',
    integrationStatus: 'roadmap',
    integrationURL: 'concur.live/integrations/oracle-rdbms',
  },
  {
    id: 33,
    integrationTitle: 'PostgreSQL',
    integrationImage: 'postgresql.png',
    integrationDescription: 'loreum ipsum text',
    integrationStatus: 'roadmap',
    integrationURL: 'concur.live/integrations/postgresql',
  },
  {
    id: 34,
    integrationTitle: 'PowerBI',
    integrationImage: 'powerbi.png',
    integrationDescription: 'loreum ipsum text',
    integrationStatus: 'roadmap',
    integrationURL: 'concur.live/integrations/powerbi',
  },
  {
    id: 35,
    integrationTitle: 'Presto',
    integrationImage: 'presto.png',
    integrationDescription: 'loreum ipsum text',
    integrationStatus: 'roadmap',
    integrationURL: 'concur.live/integrations/presto',
  },
  {
    id: 36,
    integrationTitle: 'Protobuf Schemas',
    integrationImage: 'protobuf-schemas.png',
    integrationDescription: 'loreum ipsum text',
    integrationStatus: 'roadmap',
    integrationURL: 'concur.live/integrations/protobuf-schemas',
  },
  {
    id: 37,
    integrationTitle: 'Pulsar',
    integrationImage: 'pulsar.png',
    integrationDescription: 'loreum ipsum text',
    integrationStatus: 'roadmap',
    integrationURL: 'concur.live/integrations/pulsar',
  },
  {
    id: 38,
    integrationTitle: 'Redash',
    integrationImage: 'redash.png',
    integrationDescription: 'loreum ipsum text',
    integrationStatus: 'roadmap',
    integrationURL: 'concur.live/integrations/redash',
  },
  {
    id: 39,
    integrationTitle: 'Redshift',
    integrationImage: 'redshift.png',
    integrationDescription: 'loreum ipsum text',
    integrationStatus: 'roadmap',
    integrationURL: 'concur.live/integrations/redshift',
  },
  {
    id: 40,
    integrationTitle: 'S3 Data Lake',
    integrationImage: 's3-data-lake.png',
    integrationDescription: 'loreum ipsum text',
    integrationStatus: 'roadmap',
    integrationURL: 'concur.live/integrations/s3-data-lake',
  },
  {
    id: 41,
    integrationTitle: 'SAP Hana',
    integrationImage: 'sap-hana.png',
    integrationDescription: 'loreum ipsum text',
    integrationStatus: 'roadmap',
    integrationURL: 'concur.live/integrations/sap-hana',
  },
  {
    id: 42,
    integrationTitle: 'SQLAlchemy',
    integrationImage: 'sqlalchemy.png',
    integrationDescription: 'loreum ipsum text',
    integrationStatus: 'roadmap',
    integrationURL: 'concur.live/integrations/sqlalchemy',
  },
  {
    id: 43,
    integrationTitle: 'SageMaker',
    integrationImage: 'sagemaker.png',
    integrationDescription: 'loreum ipsum text',
    integrationStatus: 'roadmap',
    integrationURL: 'concur.live/integrations/sagemaker',
  },
  {
    id: 44,
    integrationTitle: 'Salesforce',
    integrationImage: 'salesforce.png',
    integrationDescription: 'loreum ipsum text',
    integrationStatus: 'roadmap',
    integrationURL: 'concur.live/integrations/salesforce',
  },
  {
    id: 45,
    integrationTitle: 'Sharepoint',
    integrationImage: 'sharepoint.png',
    integrationDescription: 'loreum ipsum text',
    integrationStatus: 'roadmap',
    integrationURL: 'concur.live/integrations/sharepoint',
  },
  {
    id: 46,
    integrationTitle: 'Slack',
    integrationImage: 'slack.png',
    integrationDescription: 'loreum ipsum text',
    integrationStatus: 'roadmap',
    integrationURL: 'concur.live/integrations/slack',
  },
  {
    id: 47,
    integrationTitle: 'Snowflake',
    integrationImage: 'snowflake.png',
    integrationDescription: 'loreum ipsum text',
    integrationStatus: 'roadmap',
    integrationURL: 'concur.live/integrations/snowflake',
  },
  {
    id: 48,
    integrationTitle: 'Spark',
    integrationImage: 'spark.png',
    integrationDescription: 'loreum ipsum text',
    integrationStatus: 'roadmap',
    integrationURL: 'concur.live/integrations/spark',
  },
  {
    id: 49,
    integrationTitle: 'Superset',
    integrationImage: 'superset.png',
    integrationDescription: 'loreum ipsum text',
    integrationStatus: 'roadmap',
    integrationURL: 'concur.live/integrations/superset',
  },
  {
    id: 50,
    integrationTitle: 'Tableau',
    integrationImage: 'tableau.png',
    integrationDescription: 'loreum ipsum text',
    integrationStatus: 'roadmap',
    integrationURL: 'concur.live/integrations/tableau',
  },
  {
    id: 51,
    integrationTitle: 'TeraData',
    integrationImage: 'teradata.png',
    integrationDescription: 'loreum ipsum text',
    integrationStatus: 'roadmap',
    integrationURL: 'concur.live/integrations/teradata',
  },
  {
    id: 52,
    integrationTitle: 'TimescaleDB',
    integrationImage: 'timescaledb.png',
    integrationDescription: 'loreum ipsum text',
    integrationStatus: 'roadmap',
    integrationURL: 'concur.live/integrations/timescaledb',
  },
  {
    id: 53,
    integrationTitle: 'Trino',
    integrationImage: 'trino.png',
    integrationDescription: 'loreum ipsum text',
    integrationStatus: 'roadmap',
    integrationURL: 'concur.live/integrations/trino',
  },
  {
    id: 54,
    integrationTitle: 'Vertica',
    integrationImage: 'vertica.png',
    integrationDescription: 'loreum ipsum text',
    integrationStatus: 'roadmap',
    integrationURL: 'concur.live/integrations/vertica',
  },
  {
    id: 55,
    integrationTitle: 'Zendesk',
    integrationImage: 'zendesk.png',
    integrationDescription: 'loreum ipsum text',
    integrationStatus: 'roadmap',
    integrationURL: 'concur.live/integrations/zendesk',
  },
  {
    id: 56,
    integrationTitle: 'dbt',
    integrationImage: 'dbt.png',
    integrationDescription: 'loreum ipsum text',
    integrationStatus: 'roadmap',
    integrationURL: 'concur.live/integrations/dbt',
  },
];
